### PR TITLE
Update root.coffee.md

### PR DESCRIPTION
**Pull request by ymadoff**
fix selinux check causing reboot

### CODE REVIEW

**Comment by IDerr** [comment]
Hi,
this commit fixes this PR no ?
fad4ec0efae11840494806dac97f1b4402fcb536

**Comment by wdavidw** [comment]
i'm not sure

**Comment by IDerr** [comment]
I'll reopen it so.

**Comment by wdavidw** [comment]
this is not how we shall handle it anyway. There are 3 possibles values in selinux, if enabled to permissive or disable, we restart; if permissive to disable, shall we really need to restart ? Probably yes, maybe no. But this should be documented and implemented differently.

**Pull request closed without merging**
